## NUMPY Joining Arrays

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

newarr = np.concatenate((arr1, arr2))

print(newarr)

[1 2 3 4 5 6]


In [7]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

newarr = np.concatenate((arr1, arr2), axis=1)

print(newarr)

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 5)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [21]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [12, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[12, 14, 15],
       [16, 17, 18]])]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [12, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [12],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [12, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [12],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 3, 4, 4, 6, 4, 3, 2, 3, 4, 6])

x = np.where(arr==3)

print(x)

(array([ 2,  5, 10, 12], dtype=int64),)


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2==0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2==1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 7])

x = np.searchsorted(arr, 7)

print(x)

3


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 7])

x = np.searchsorted(arr, 7, side='right')

print(x)

4


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 7])

x = np.searchsorted(arr, [2, 4, 5])

print(x)

[1 3 3]


In [36]:
import numpy as np

arr = np.array([3, 2, 5, 7, 8, 0])

x = np.sort(arr)

print(x)

[0 2 3 5 7 8]


In [37]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

x = np.sort(arr)

print(x)

['apple' 'banana' 'cherry']


In [38]:
import numpy as np

arr = np.array([True, False, True])

x = np.sort(arr)

print(x)

[False  True  True]


In [39]:
import numpy as np

arr = np.array([[8, 3, 5], [9, 5, 2]])

x = np.sort(arr)

print(x)

[[3 5 8]
 [2 5 9]]


In [43]:
import numpy as np

arr = np.array([39, 42, 56, 12])

x = arr[[False, True, True, False]]

print(x)

[42 56]


In [44]:
import numpy as np

arr = np.array([23, 78, 54, 34])

# create a empty array

filter_arr = []

# go through each element in an array

for element in arr:
    # if the element is higher than 42, set the value to true, otherwise false
    
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print(newarr)


[78 54]


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# create an empty list

filter_arr = []

# go through the each element of an array
    
for element in arr:
    # if the element is completly divisible by 2, set the value to true, otherwise false
    
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print(newarr)

[2 4 6 8]


In [47]:
import numpy as np

arr = np.array([45, 34, 56, 67, 23])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)

print(newarr)

[ True False  True  True False]
[45 56 67]


In [48]:
import numpy as np

arr = np.array([45, 34, 56, 67, 23])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)

print(newarr)

[False  True  True False False]
[34 56]
