## NUMPY Array Slicing

In [1]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5, 6, 7])

print(arr[2:5])

[3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5, 6, 7])

print(arr[2:])

[3 4 5 6 7]


In [4]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5, 6, 7])

print(arr[:2])

[1 2]


In [5]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5, 6, 7])

print(arr[-5:-2])

[3 4 5]


In [6]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5, 6, 7])

print(arr[3: 7: 2])

[4 6]


In [7]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 2:5])

[ 8  9 10]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2:5])

[[ 3  4  5]
 [ 8  9 10]]


#### Consider the following code:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:2])
What will be the printed result?

* [1]
* [1 2]
* [1 2 3]
* [3 4 5 6 7]

#### Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the second item to (not including) the fifth item.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr___)

#### Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the third item to (not including) the fifth item.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr___)

#### Insert the correct slicing syntax to print the following selection of the array:

Every other item from (including) the second item to (not including) the fifth item.

Tip: use the step syntax.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr____)

#### Insert the correct slicing syntax to print the following selection of the array:

Every other item from the entire array.

Tip: use the step syntax.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr____)

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

int32


In [2]:
import numpy as np

arr = np.array(["apple", "banana", "mango", "graps"])

print(arr.dtype)

<U6


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype='S')

print(arr)

print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)

print(arr.dtype)

[1 2 3 4]
int32


In [6]:
import numpy as np

arr = np.array('1', '2', '3', '4', dtype='i')

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [7]:
import numpy as np

arr = np.array([1.1, 2.1, 3.2, 4.6])

newarr = arr.astype('i')

print(newarr)

print(newarr.dtype)

[1 2 3 4]
int32


In [8]:
import numpy as np

arr = np.array([1.1, 2.1, 3.2, 4.6])

newarr = arr.astype(int)

print(newarr)

print(newarr.dtype)

[1 2 3 4]
int32


In [9]:
import numpy as np

arr = np.array([1, 0, 7])

newarr = arr.astype(bool)

print(newarr)

print(newarr.dtype)

[ True False  True]
bool


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

arr[0] = 43

print(arr)

print(x)

[43  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.view()

x[0] = 78

print(arr)

print(x)

[78  2  3  4  5]
[78  2  3  4  5]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

y = arr.view()

print(x.base)

print(y.base)

None
[1 2 3 4 5]


In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)

print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
