## NUMPY Introduction

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### What does NumPy stand for?

* Number Picker
* Numerical Platform
* Numerical Python

#### What is the array object in NumPy called?

* ndarray
* ar
* numarr

#### True or False. NumPy is an open source project and you can use it freely.

* True
* False

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np

print(np.__version__)

1.26.4


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np

arr = np.array(45)

print(arr)

45


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
import numpy as np

a = np.array(45)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)

print("number of dimensions: ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions:  5


#### Consider the following array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
How many dimensions does it have?

* 1
* 2
* 3

#### Insert the correct method for creating a NumPy array.

* arr = np.___([1, 2, 3, 4, 5])

#### Insert the correct argument for creating a NumPy array with 2 dimensions.

* arr = np.array([1, 2, 3, 4], ___=2)

#### Insert the correct syntax for checking the number of dimension of a NumPy array.

* arr = np.array([1, 2, 3, 4])

* print(arr.___)

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[0])

1


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[1])

2


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[2] + arr[4])

8


In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Second element of first row:", arr[0, 1])

Second element of first row: 2


In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Fith element of second row:", arr[1, 3])

Fith element of second row: 9


In [29]:
import numpy as np

#                0          1      2
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [31]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Last element from second dimension :", arr[1, -1])

Last element from second dimension : 8


#### Consider the following code:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])
What will be the printed result?

* 1
* 3
* 7
* 8

#### arr = np.array([1, 2, 3, 4, 5])

* print(arr___)

#### Insert the correct syntax for printing the number 50 from the array.

arr = np.array([10, 20, 30, 40, 50])

print(arr____)

#### Insert the correct syntax for printing the number 50 from the array.

arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

print(arr___)

#### Use negative index to print the last item in the array.

arr = np.array([10, 20, 30, 40, 50])

print(arr___)